"""add_requires_extra_fields_to_tasks_and_change_time_entries

Revision ID: 002_phase_5_and_6
Revises: 001_initial_schema
Create Date: 2026-03-05 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_phase_5_and_6'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add requires_extra_fields to tasks
    op.add_column('tasks', sa.Column('requires_extra_fields', sa.Boolean(), server_default='false', nullable=False))
    
    # 2. Rename columns in time_entries
    op.alter_column('time_entries', 'vehicle_used', new_column_name='vehicle_type')
    op.alter_column('time_entries', 'meals_allowance', new_column_name='meals')
    op.alter_column('time_entries', 'distance_from', new_column_name='distance_origin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'distance_origin', new_column_name='distance_from')
    op.alter_column('time_entries', 'meals', new_column_name='meals_allowance')
    op.alter_column('time_entries', 'vehicle_type', new_column_name='vehicle_used')
    op.drop_column('tasks', 'requires_extra_fields')
    # ### end Alembic commands ###
